green_turtle = Turtle("turtle")
# blue_turtle = Turtle("turtle")
# purple_turtle = Turtle("turtle")
# yellow_turtle = Turtle("turtle")
# black_turtle = Turtle("turtle")
# brown_turtle = Turtle("turtle")